# Generated by Django 5.1.6 on 2025-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('category', models.CharField(choices=[('public', 'Государственная'), ('private', 'Частная'), ('special', 'Специальная')], default='public', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_images/')),
            ],
        ),
    ]
