# Generated by Django 5.1.6 on 2025-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
