# Generated by Django 5.1.6 on 2025-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(choices=[('central', 'Центральный район'), ('north', 'Северный район'), ('east', 'Восточный район'), ('west', 'Западный район')], default='central', max_length=10),
        ),
    ]
